spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

resend:
  api-key: ${RESEND_API_KEY}

admin:
  username: ${ADMIN_USERNAME}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

app:
  cookie:
    secure: ${APP_COOKIE_SECURE:false}
  email:
    from: ${APP_EMAIL_FROM:noreply@samkelongcobo.is-a.dev}
    admin: ${ADMIN_EMAIL:samkelop.dev@gmail.com}
    webapp-url: ${APP_WEBAPP_URL:https://samkelongcobo.is-a.dev}